apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-om-playground-api
  name: redis-om-playground-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-om-playground-api
  template:
    metadata:
      labels:
        app: redis-om-playground-api
    spec:
      containers:
      - image: localhost:5001/redis-om-playground-api:latest
        imagePullPolicy: Always
        name: redis-om-playground-api
        env:
        - name: ConnectionStrings__RedisOs
          valueFrom:
            secretKeyRef:
              key: connection-string
              name: redis-authentication
        - name: RoutingConfiguration__PathBase
          value: "/<pathbase>"  # Replace <pathbase> with the actual path base
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi